export const SIGNUP_REQ = 'SIGNUP_REQ'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const SIGNIN_REQ = 'SIGNIN_REQ'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNINT_FAIL'

export const SIGNOUT_REQ = 'SIGNOUT_REQ'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL'